name: Release jfvm to Homebrew

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g. v2.0.0)'
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Determine tag to release
        id: tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Detected manual run"
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "Detected tag push"
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Build binaries for all platforms
        run: |
          mkdir -p dist
          
          # Build for macOS AMD64
          GOOS=darwin GOARCH=amd64 go build -o dist/jfvm-darwin-amd64 .
          
          # Build for macOS ARM64
          GOOS=darwin GOARCH=arm64 go build -o dist/jfvm-darwin-arm64 .
          
          # Build for Linux AMD64
          GOOS=linux GOARCH=amd64 go build -o dist/jfvm-linux-amd64 .
          
          # Build for Linux ARM64
          GOOS=linux GOARCH=arm64 go build -o dist/jfvm-linux-arm64 .
          
          # Make all binaries executable
          chmod +x dist/jfvm-*
          
          # Create tar.gz archive for Homebrew
          cd dist
          tar -czf jfvm-${{ steps.tag.outputs.tag }}.tar.gz jfvm-*
          cd ..
          
          # Debug: List all files in dist directory
          echo "=== Files in dist directory ==="
          ls -la dist/
          echo "=== Tar.gz file details ==="
          ls -la dist/jfvm-${{ steps.tag.outputs.tag }}.tar.gz

      - name: Test binaries
        run: |
          echo "Testing built binaries..."
          ./dist/jfvm-darwin-amd64 --version
          ./dist/jfvm-darwin-arm64 --version

      - name: Debug upload files
        run: |
          echo "=== Checking tar.gz file to upload ==="
          echo "Tag: ${{ steps.tag.outputs.tag }}"
          echo "Checking tar.gz file:"
          ls -la dist/jfvm-${{ steps.tag.outputs.tag }}.tar.gz

      - name: Upload GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: "jfvm ${{ steps.tag.outputs.tag }}"
          body: |
            ## What's New
            
            This release includes:
            - Multi-platform support (macOS ARM64/AMD64, Linux ARM64/AMD64)
            - JFrog CLI version management
            - Homebrew integration
            
            ## Downloads
            
            The tar.gz archive contains binaries for all platforms:
            - macOS (Intel and Apple Silicon)
            - Linux (Intel and ARM)
          files: |
            dist/jfvm-${{ steps.tag.outputs.tag }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false



