name: Test Homebrew Installation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-brew-installation:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up shell environment
        run: |
          # Ensure we're using the right shell for CI
          echo "=== Setting up shell environment ==="
          echo "Default shell: $SHELL"
          echo "Current shell: $(basename $SHELL)"
          
          # GitHub Actions uses bash by default
          # On macOS, the system might have zsh as default, but we'll use bash for CI
          echo "Using bash for CI environment"
          export SHELL=/bin/bash
          
          echo "Final shell: $SHELL"
          
          # Show existing shell profiles for debugging
          echo "=== Checking existing shell profiles ==="
          for profile in ~/.bash_profile ~/.bashrc ~/.zshrc; do
            if [ -f "$profile" ]; then
              echo "Found existing profile: $profile"
              echo "=== Contents of $profile ==="
              cat "$profile" || echo "Could not read $profile"
              echo "=== End of $profile ==="
            fi
          done

      - name: Install jfcm via Homebrew
        run: |
          # Debug: Check shell environment
          echo "=== Shell Environment Check ==="
          echo "SHELL: $SHELL"
          echo "Shell name: $(basename $SHELL)"
          echo "Available shells:"
          cat /etc/shells || echo "Cannot read /etc/shells"
          
          # Add the jfrog tap
          brew tap jfrog/jfrog-cli-vm || echo "Tap already exists or failed"
          
          # Install jfcm
          brew install jfcm || echo "Installation failed, trying to continue"
          
          # Verify installation
          jfcm --version || echo "jfcm not found in PATH"

      - name: Install test jf binary
        run: |
          # Install a test version of jf for testing
          jfcm install 2.74.0
          
          # Verify jf binary exists
          ls -la ~/.jfcm/versions/2.74.0/jf
          
          # Test the binary directly
          ~/.jfcm/versions/2.74.0/jf --version

          jfcm health-check --fix --verbose

      - name: Setup shell environment
        run: |
          # Debug: Show shell information
          echo "=== Shell Information ==="
          echo "Current shell: $SHELL"
          echo "Shell name: $(basename $SHELL)"
          echo "Current PATH: $PATH"
          
          # Export jfcm PATH manually for CI environment
          export PATH="$HOME/.jfcm/shim:$PATH"
          
          # Verify jfcm is in PATH
          echo "PATH entries:"
          echo $PATH | tr ':' '\n' | grep jfcm || echo "No jfcm entries found"
          
          # Test jfcm command
          jfcm --version

      - name: Test basic functionality
        run: |
          # Test help command
          jfcm --help || echo "Help command failed"
          
          # Test list command
          jfcm list || echo "List command failed"
          
          # Test health check
          jfcm health-check || echo "Health check failed"

      - name: Test enhanced priority system
        run: |
          # Ensure jfcm PATH is loaded
          export PATH="$HOME/.jfcm/shim:$PATH"
          
          # Use the version
          jfcm use 2.74.0 || echo "jfcm use failed"
          
          # Verify which jf is being used
          which jf || echo "jf not found in PATH"
          
          # Test jf execution
          jf --version || echo "jf execution failed"
          
          # Run health check to verify priority
          jfcm health-check --verbose || echo "Health check failed"

      - name: Test health check with fixes
        run: |
          # Ensure jfcm PATH is loaded
          export PATH="$HOME/.jfcm/shim:$PATH"
          
          # Test health check with fix flag
          jfcm health-check --fix
          
          # Verify PATH configuration
          echo "PATH entries:"
          echo $PATH | tr ':' '\n' | grep jfcm || echo "No jfcm entries found"
          
          # Test which jf again
          which jf

          # Test jf execution again
          jf --version

      - name: Test alias functionality
        run: |
          # Ensure jfcm PATH is loaded
          export PATH="$HOME/.jfcm/shim:$PATH"
          
          # Create an alias
          jfcm alias set test-alias 2.74.0
          
          # Use the alias
          jfcm use test-alias
          
          # Verify alias works
          jf --version

      - name: Test project-specific version
        run: |
          # Ensure jfcm PATH is loaded
          export PATH="$HOME/.jfcm/shim:$PATH"
          
          # Create a .jfrog-version file
          echo "2.74.0" > .jfrog-version
          
          # Use without arguments (should read from .jfrog-version)
          jfcm use
          
          # Verify correct version is active
          jf --version
          
          # Clean up
          rm .jfrog-version

      - name: Test performance and security checks
        run: |
          # Ensure jfcm PATH is loaded
          export PATH="$HOME/.jfcm/shim:$PATH"
          
          # Test health check with performance and security flags
          jfcm health-check --performance --security --verbose

      - name: Test error handling
        run: |
          # Ensure jfcm PATH is loaded
          export PATH="$HOME/.jfcm/shim:$PATH"
          
          # Test using non-existent version
          jfcm use non-existent-version || echo "Expected error for non-existent version"
          
          # Test using invalid alias
          jfcm use invalid-alias || echo "Expected error for invalid alias"
          
      - name: Test latest version functionality
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Ensure jfcm PATH is loaded
          export PATH="$HOME/.jfcm/shim:$PATH"
          jfcm health-check --fix
          
          # Test using latest version
          jfcm use latest || echo "jfcm use latest failed"
          
          # Verify latest version is active
          jf --version || echo "jf execution failed"
          
          # Check health status
          jfcm health-check || echo "Health check failed"

      - name: Verify final state
        run: |
          # Ensure jfcm PATH is loaded
          export PATH="$HOME/.jfcm/shim:$PATH"
          
          # Final health check
          jfcm health-check
          
          # List installed versions
          jfcm list
          
          # Show which jf is active
          which jf
          jf --version
          
          # Show PATH entries
          echo "Final PATH entries:"
          echo $PATH | tr ':' '\n' | grep jfcm || echo "No jfcm entries found"

      - name: Cleanup
        if: always()
        run: |
          # Uninstall jfcm
          brew uninstall jfcm || true
          
          # Remove tap
          brew untap jfrog/jfrog-cli-vm || true 