name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run unit tests
        run: |
          # Run unit tests only (exclude E2E tests that require built binary)
          go test -v ./cmd/... ./internal/...

  test-e2e-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build jfvm
        run: |
          make build-release
          chmod +x jfvm

      - name: Debug Profile Contents
        run: |
          echo "=== Ubuntu Runner Information ==="
          echo "Runner ID: $RUNNER_ID"
          echo "Runner Name: $RUNNER_NAME"
          echo "Run ID: $GITHUB_RUN_ID"
          echo "Run Number: $GITHUB_RUN_NUMBER"
          echo "Job: $GITHUB_JOB"
          echo "Hostname: $(hostname)"
          echo "Timestamp: $(date)"
          echo ""
          
          echo "=== Ubuntu Profile Contents ==="
          if [ -f /home/runner/.bash_profile ]; then
            echo "Lines in .bash_profile:"
            wc -l /home/runner/.bash_profile
            echo "First 20 lines:"
            head -20 /home/runner/.bash_profile
            echo "Last 20 lines:"
            tail -20 /home/runner/.bash_profile
          else
            echo ".bash_profile does not exist"
          fi
          
          if [ -f /home/runner/.bashrc ]; then
            echo "Lines in .bashrc:"
            wc -l /home/runner/.bashrc
            echo "First 20 lines:"
            head -20 /home/runner/.bashrc
            echo "Last 20 lines:"
            tail -20 /home/runner/.bashrc
          else
            echo ".bashrc does not exist"
          fi

      - name: Run E2E tests
        env:
          JFVM_PATH: ${{ github.workspace }}/jfvm
          TEST_TIMEOUT: "10m"
        run: |
          go test -v -timeout 10m ./tests/e2e/...

  test-e2e-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build jfvm
        run: |
          make build-release
          chmod +x jfvm

      - name: Test enhanced priority system
        env:
          JFVM_PATH: ${{ github.workspace }}/jfvm
        run: |
          # Install a test version
          ./jfvm install 2.74.0
          
          # Use the version
          ./jfvm use 2.74.0
          
          # Export jfvm shim to PATH directly (avoid shell profile issues)
          export PATH="$HOME/.jfvm/shim:$PATH"
          
          # Verify which jf is being used
          which jf
          
          # Test jf execution
          jf --version
          
          # Run health check to verify priority
          ./jfvm health-check --verbose

      - name: Test health check with fixes
        env:
          JFVM_PATH: ${{ github.workspace }}/jfvm
        run: |
          # Test health check with fix flag
          ./jfvm health-check --fix
          
          # Export jfvm shim to PATH directly (avoid shell profile issues)
          export PATH="$HOME/.jfvm/shim:$PATH"
          
          # Verify PATH configuration
          echo "PATH entries:"
          echo $PATH | tr ':' '\n' | grep jfvm || echo "No jfvm entries found"
          
          # Test which jf again
          which jf
          
          # Final health check
          ./jfvm health-check

      - name: Debug Profile Contents Before E2E
        run: |
          echo "=== macOS E2E Profile Contents ==="
          if [ -f /Users/runner/.bash_profile ]; then
            echo "Lines in .bash_profile:"
            wc -l /Users/runner/.bash_profile
            echo "First 20 lines:"
            head -20 /Users/runner/.bash_profile
            echo "Last 20 lines:"
            tail -20 /Users/runner/.bash_profile
          else
            echo ".bash_profile does not exist"
          fi
          
          if [ -f /Users/runner/.zshrc ]; then
            echo "Lines in .zshrc:"
            wc -l /Users/runner/.zshrc
            echo "First 20 lines:"
            head -20 /Users/runner/.zshrc
            echo "Last 20 lines:"
            tail -20 /Users/runner/.zshrc
          else
            echo ".zshrc does not exist"
          fi

      - name: Run E2E tests
        env:
          JFVM_PATH: ${{ github.workspace }}/jfvm
          TEST_TIMEOUT: "10m"
        run: |
          go test -v -timeout 10m ./tests/e2e/...

  test-brew-installation:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install jfvm via Homebrew
        run: |
          # Add the jfrog tap
          brew tap jfrog/jfrog-cli-vm
          
          # Install jfvm
          brew install jfvm
          
          # Verify installation
          jfvm --version

      - name: Test enhanced priority system
        run: |
          # Install a test version
          jfvm install 2.74.0
          
          # Use the version
          jfvm use 2.74.0
          
          # Export jfvm shim to PATH directly (avoid shell profile issues)
          export PATH="$HOME/.jfvm/shim:$PATH"
          
          # Verify which jf is being used
          which jf
          
          # Test jf execution
          jf --version
          
          # Run health check to verify priority
          jfvm health-check --verbose

      - name: Test health check with fixes
        run: |
          # Test health check with fix flag
          jfvm health-check --fix
          
          # Export jfvm shim to PATH directly (avoid shell profile issues)
          export PATH="$HOME/.jfvm/shim:$PATH"
          
          # Verify PATH configuration
          echo "PATH entries:"
          echo $PATH | tr ':' '\n' | grep jfvm || echo "No jfvm entries found"
          
          # Test which jf again
          which jf
          
          # Final health check
          jfvm health-check

      - name: Debug Profile Contents Before Latest Test
        run: |
          echo "=== Brew Installation Profile Contents ==="
          if [ -f /Users/runner/.bash_profile ]; then
            echo "Lines in .bash_profile:"
            wc -l /Users/runner/.bash_profile
            echo "First 20 lines:"
            head -20 /Users/runner/.bash_profile
            echo "Last 20 lines:"
            tail -20 /Users/runner/.bash_profile
          else
            echo ".bash_profile does not exist"
          fi
          
          if [ -f /Users/runner/.zshrc ]; then
            echo "Lines in .zshrc:"
            wc -l /Users/runner/.zshrc
            echo "First 20 lines:"
            head -20 /Users/runner/.zshrc
            echo "Last 20 lines:"
            tail -20 /Users/runner/.zshrc
          else
            echo ".zshrc does not exist"
          fi

      - name: Test latest version functionality
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Debug: Show runner information
          echo "=== Runner Information ==="
          echo "Runner ID: $RUNNER_ID"
          echo "Runner Name: $RUNNER_NAME"
          echo "Run ID: $GITHUB_RUN_ID"
          echo "Run Number: $GITHUB_RUN_NUMBER"
          echo "Job: $GITHUB_JOB"
          echo "Hostname: $(hostname)"
          echo "Timestamp: $(date)"
          echo ""
          
          # Debug: Show profile contents before any operations
          echo "=== Profile Contents Before Operations ==="
          if [ -f /Users/runner/.bash_profile ]; then
            echo "Lines in .bash_profile:"
            wc -l /Users/runner/.bash_profile
            echo "First 20 lines:"
            head -20 /Users/runner/.bash_profile
            echo "Last 20 lines:"
            tail -20 /Users/runner/.bash_profile
          else
            echo ".bash_profile does not exist"
          fi
          echo ""
          
          # Check health status and fix issues
          echo "=== Running Health Check with Fix ==="
          jfvm health-check --fix --verbose
          echo ""
          
          # Debug: Show profile contents after health check
          echo "=== Profile Contents After Health Check ==="
          if [ -f /Users/runner/.bash_profile ]; then
            echo "Lines in .bash_profile:"
            wc -l /Users/runner/.bash_profile
            echo "First 20 lines:"
            head -20 /Users/runner/.bash_profile
            echo "Last 20 lines:"
            tail -20 /Users/runner/.bash_profile
          else
            echo ".bash_profile does not exist"
          fi
          echo ""
          
          # Test syntax validation
          echo "=== Testing Profile Syntax ==="
          if [ -f /Users/runner/.bash_profile ]; then
            if bash -n /Users/runner/.bash_profile; then
              echo "✅ Profile syntax is valid"
            else
              echo "❌ Profile syntax is invalid"
              echo "Showing problematic lines:"
              bash -n /Users/runner/.bash_profile 2>&1 || true
            fi
          fi
          echo ""
          
          # Only source if syntax is valid
          echo "=== Sourcing Profile ==="
          if [ -f /Users/runner/.bash_profile ]; then
            if bash -n /Users/runner/.bash_profile; then
              echo "Sourcing .bash_profile..."
              source /Users/runner/.bash_profile
            else
              echo "Skipping source due to syntax errors"
            fi
          fi

          # Test using latest version
          jfvm use latest
          
          # Verify latest version is active
          jf --version
          

      - name: Test performance and security checks
        run: |
          # Test health check with performance and security flags
          jfvm health-check --performance --security --verbose

      - name: Cleanup
        if: always()
        run: |
          # Uninstall jfvm
          brew uninstall jfvm || true
          
          # Remove tap
          brew untap jfrog/jfrog-cli-vm || true

  test-integration:
    runs-on: ubuntu-latest
    needs: [test-unit, test-e2e-ubuntu]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build and test integration
        run: |
          make build-release
          chmod +x jfvm
          
          # Test basic functionality
          ./jfvm --help
          ./jfvm list
          ./jfvm health-check
          
          # Test that binary works correctly
          ./jfvm --version

  upload-artifacts:
    runs-on: ubuntu-latest
    needs: [test-unit, test-e2e-ubuntu, test-e2e-macos, test-brew-installation, test-integration]
    if: always()
    steps:
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results-*.json
            coverage-reports/
          retention-days: 7 